
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


name: progran
accessor:
  username: xosadmin@opencord.org
  password: "@/opt/xos/services/progran/credentials/xosadmin@opencord.org"
required_models:
  - ProgranService
  - ProgranServiceInstance
  - MCordSubscriberInstance
  - ENodeB
  - Handover
dependency_graph: "/opt/xos/synchronizers/progran/model_deps"
steps_dir: "/opt/xos/synchronizers/progran/steps"
sys_dir: "/opt/xos/synchronizers/progran/sys"
#model_policies_dir: "/opt/xos/synchronizers/progran/model_policies"


keep_temp_files: True

logging:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
    file:
      class: logging.handlers.RotatingFileHandler
      filename: /var/log/xos.log
      maxBytes: 10485760
      backupCount: 5
  loggers:
    '':
      handlers:
          - console
          - file
      level: DEBUG